volumes:
  pg_data: { }

services:
  postgres:
    container_name: local-postgres
    image: "postgres:13.1-alpine"
    restart: on-failure
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - pgsql-env

  lemur:
    container_name: local-lemur
    image: "lemur:local-dev"
    restart: on-failure
    build:
      context: ../
      dockerfile: ./local/Dockerfile
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
    env_file:
      - lemur-env
      - pgsql-env
    ports:
      - "8087:80"
      - "8447:443"

  redis:
    container_name: local-redis
    image: "redis:alpine3.12"
    restart: on-failure
